### ISSUE TITLE
A module should not be trying to write to the python install directory!

### ISSUE THREAD

**Issue by bryanherger** [vertica/VerticaPy#125]
From customer:
I think this wants fixing…

from verticapy.connect import *
new_auto_connection(
    {"host": "dbvert", "port": "5433", "database": "vdb1", "password": password, "user": "dbadmin"},
    name = "xxx"
)

PermissionError: [Errno 13] Permission denied: '/opt/miniconda3/envs/py37_PROD_20210518_RLH_V1/lib/python3.7/site-packages/verticapy/connections.verticapy'

A module should not be trying to write to the python install directory!

In https://github.com/vertica/VerticaPy/blob/master/verticapy/connect.py, it's probably better to write this to the user's HOME rather than the site-modules path, e.g.:
from os.path import expanduser
home = expanduser("~")

**Comment by bryanherger** [comment]
Amended requests from customer:
The save file location should be configurable, with default to user home.
The default permissions should probably be same as for SSH keys, where there’s a hidden dir “.verticapy” with mode 700, with the connection file itself 600.  We can’t leave connection info site-packages which is typically world-readable.

**Comment by oualib** [comment]
The problem is that we will need to know an exact location where to find the credentials. Let's say you want to write the connection in folder "x", how can we know that we have to search there? So at least something must be written somewhere, it can be a global env variable or in the verticapy directory of which we always know the location. Many API are using DSN but it is quite different there as you may want to add some extra parameters to vertica-python cursor.
If you find a good solution to that, we can add it to the next release.
Raghu got the exact same problem and he managed to solve it easily. @bryanherger what do you propose?

**Comment by oualib** [comment]
In v0.6.3, it will write a new directory in the $VERTICAPY dir. If it does not exist then it will write a new dir in the $HOME dir. However, this folder and the file inside can not be hidden due to Python limitations in terms of users privileges.
