### ISSUE TITLE
vdf_from_relation: `order by` might work, might not work

### ISSUE THREAD

**Issue by iamdionysus** [vertica/VerticaPy#146]
When I include `order by` clause in vdf_from_relation function, I see that order by working in some case and not working in the other case. Can `order by` be working inside vdf_from_relation sql query itself?

**Comment by oualib** [comment]
The last "order by" statement will work inside a nested query only when using 1 single node. When using multiple nodes, as Vertica does not work with indexes, the data might not be sorted. That's why you should use the 'sort' method after creating the vDataFrame. I will see if we can extract the last order by statement to do it automatically.

**Comment by oualib** [comment]
After looking at the possibilities, it can not be implemented (explained above).

This is a possible solution:
```python
# Sorting inside will not sort the final output
# vdf = vdf_from_relation("(SELECT age, fare FROM titanic ORDER BY age) x")

# Creating the vDataFrame
vdf = vdf_from_relation("(SELECT age, fare FROM titanic) x")
# Sorting the result (explicit ORDER BY)
vdf.sort("age")
```

You can also use the 'readSQL'  function directly.
```python
readSQL("SELECT age, fare FROM titanic ORDER BY age")
```

**Comment by iamdionysus** [comment]
I tried `readSQL` and found that I can do the `order by` as I wanted. However, I tend to use more `vdf_from_relation`, so I was wondering if this could be possible. Thanks for the feedback anyway.
