### ISSUE TITLE
Feature Importance in Logistic Regression

### ISSUE THREAD

**Issue by SMoazzamR** [vertica/VerticaPy#17]
It can be seen from the image that features importance calculated by VerticaPy is ABS(Coefficient * (max - min)) but this implementation is not supported for columns which are of different scales i.e Column A have min=-200 max=100 with coef=0.2 and Column B have min=1 and max=8 with coef=0.9.

Coef
Column A 0.2
Column B 0.9

Importance (VerticaPy)
Column A 60
Column B 6.3

It can be seen that both columns have different coefficients and very different ranges of data but when importance is calculated then column with high range of values dominate over coefficients.

Can you please justify the approach used by VerticaPy to calculate the feature importance.

![image](https://user-images.githubusercontent.com/58803788/91558243-6c7c6000-e94f-11ea-9286-1242e68a2639.png)

**Comment by oualib** [comment]
Its written just above: "Computes the model features importance by normalizing the Logit coefficients".
Example: Let's say you computed your Logit. f(x1 ... xn) = f(a0 + a1 * x1 + a2 * x2 ... + an * xn).
So f(x1 ... xn) = f(a0 + (a1 * (max(x1) - min(x1))) * (x1 / (max(x1) - min(x1))) + (a2 * (max(x2) - min(x2))) * (x2 / (max(x2) - min(x2))) + ...)
By setting Xi = (xi / (max(xi) - min(xi))) and Ai = (ai * (max(xi) - min(xi))), we now have:
f(x1 ... xn) = F(X1 ... Xn) but now the Xi live in [0, 1]. The higher is their coefficient the more they can influence the decision. Remember that there is no perfect "features_importance" value but this one is fair enough. p-value can also be used but they exist just to reject some coefficient and not to tell that one is more important than another.

Hope it helps!

**Comment by SMoazzamR** [comment]
Thanks for such an explanation but my point is still not cleared i.e when the scales and ranges of columns are ranges then how can we decide which column is more important than another. I know that if scales are the same then only the coefficient value indicates importance but if you go through my example provided above you can see that the coefficient has nothing to do with importance if the value ranges are different among columns.

**Comment by oualib** [comment]
Hi @SMoazzamR,

The coefficient is of course took into account! The new importance is a combination between the coefficient and the variable range. 

Ai = (ai * (max(xi) - min(xi)))

If the variable scale in 0,1 then the importance is the coefficient itself, otherwise we have to multiply it by the range. Imagine the following use-case:

Column A have min=-20 max=10 with coef=0.2 and Column B have min=1 and max=8 with coef=0.9.

Then Imp(A) = 30 * 0.2 = 6 and Imp(B) = 0.9 * 9 = 8.1 so B is still more important. This score is ofc at the end normalized to get a sum equals to 100.

The importance in this case is how the variable can influence the prediction, how it can unbalanced the result of the Logit(X) function.

Hope it answers to your question,

Best,

Badr
