### ISSUE TITLE
Scatter Geospatial Example does not work

### ISSUE THREAD

**Issue by liv4unix** [vertica/VerticaPy#190]
This example :
https://www.vertica.com/python/gallery/scatter_geo/

1) Needs geopandas installed (3rd party tools should be noted in the example documentation). 
2) Also, the example does not work as written as it appears to be missing a second dataset (africa_education):

AssertionError: No table or views 'africa_education' found.

Where is the data for the "africa" dataframe supposed to be coming from?
africa = vDataFrame("africa_education")

**Comment by oualib** [comment]
Hi @liv4unix,

Thanks a lot for your feedback.
The dataset is available from this example: https://www.vertica.com/python/examples/africa_education/index.php
We are not forcing users to install extensions as explained in the documentation:
https://www.vertica.com/python/installation.php#title_6
If you want all the extensions to be installed you can run:
pip3 install verticapy[all]
Otherwise, everything is mentioned in the setup.

We will work on making this example, easier to make. It will be updated when we will release the v0.8.1.

Badr
