### ISSUE TITLE
KernelDensity

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#211]
Hello,

When we use 2 times the function KernelDensity, we don't have the same results.

When you use tree function, you have max_features=sqrt, but we must have max_features = max for this function. 

The other problem is that this funtion create 2 models and 1 table, not juste 1 model. For "name" parameter, if we enter schema + ".kerneld_iris", we have : 
schema + ".kerneld_iris" model
schema + ".kerneld_iris_KernelDensity_Tree" model
schema + ".kerneld_iris_KernelDensity_Map" table

I think the last 2 shoud be drop. 

Regards,

Alexandre

**Comment by oualib** [comment]
Due to the complexity of KDE, we found a way to compute it using different relations. At the end 2 elements are created:
 - a KDE table using multiple steps to compute as many points as possible
 - a RF model to learn on the table the distribution
The table can be dropped but it is used by some specific functions.
In the next PR, we change the value max_features to set it to max and close the issue.
