### ISSUE TITLE
logistique regression

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#221]
Hello,

When we launch 2 times the same logistic regression, we don't have the same result. 

For exemple, with titanic dataset : 

```
from verticapy.learn.linear_model import LogisticRegression
drop(schema + ".lr_titanic", cursor = cur, method = "model")
model1 = LogisticRegression(name = schema + ".lr_titanic", penalty = 'None')
model1.fit(titanic_copy, ["fare", "age"], "survived")

drop(schema + ".lr_titanic", cursor = cur, method = "model")
model2 = LogisticRegression(name = schema + ".lr_titanic", penalty = 'None')
model2.fit(titanic_copy, ["fare", "age"], "survived")
```

the results are : 

![image](https://user-images.githubusercontent.com/49387599/153002487-72737178-2c67-4b45-952b-0c3dc532bad0.png)

We see few differences on the coefficients. The dataset titanic is very simple, but on larger dataset, the differences are larger. 

The problem seem to come from "LOGISTIC_REG", a vertica function. I don't know why and if you can fix that? 

Regards, 

Alexandre

**Comment by afard** [comment]
Hi Alexandre,

Thanks for your report.

I'd like to highlight that the differences on the coefficients in your reported experiment are smaller than 1e-12. This is an inevitable [roundoff error](https://en.wikipedia.org/wiki/Round-off_error) caused by the distributed algorithm that trains the logistic-regression model.

In fact, when the LOGISTIC_REG function is called, multiple parallel threads collaborate to calculate the resulted coefficients in several iterations. The number of threads is determined by the number of Vertica nodes and available resources (i.e., the number of processing cores per node, the available amount of memory in the corresponding resource pool, and the load imposed by other concurrent queries). Even in the experiments with the same running environment and the same number of threads, parallel threads may finish processing their assigned data in different orders in each run. This means that their interval calculated results would be aggregated in different order each time. This would consequently lead to slightly different final results in different runs due to roundoff error.

We have tested the LOGISTIC_REG function on different Vertica clusters and different data sizes and we have not observed more than 1e-9 difference in the trained coefficients.

Regards,
Arash
