### ISSUE TITLE
Rolling windows borders

### ISSUE THREAD

**Issue by antoinemertz** [vertica/VerticaPy#486]
Hi,

I'm working with VerticaPy 0.8.1 (new versions 0.12 is tested but not yet available for me).
And I've some trouble understanding the rolling method used with specific windows.

For example with a toy dataset of 8 lines:

![image](https://user-images.githubusercontent.com/26509655/223375510-6eedab50-cd72-4ab1-b2fb-eadad4a2db9f.png)

![image](https://user-images.githubusercontent.com/26509655/223375601-e430f0e3-9efe-4517-bafb-1e384bc7f69c.png)

I want to average the column value by idt with the value of the 3 preceding months (without the actual one). So I run the rolling method with `window = ("-3months", "-1months")` and this is the result I have:

![image](https://user-images.githubusercontent.com/26509655/223376005-9ecea5fc-e559-49e6-9779-16e2380b49cb.png)

And I was expected on another value for the column `avg_value` for `idt=1 and date='2023-02-01'`. For me it should average the 3 preceding months so give back the average of 85, 80 and 75 so 80 and not 77.5. It seems that it doens't take the value of 2022-11-01 but 3 months before 2023-02-01 is exactly 2022-11-01 so I don't understand why it is not taken in the result.

Is it a normal behavior?

Thanks in advance for your response and thanks for your work,

Antoine

**Comment by oualib** [comment]
Hi @antoinemertz,

Weird. It seems to be more server-side oriented. Maybe they translate 'month' to a well defined unit (like number of seconds ...) and during this translation there are some wrong assumptions like 1 month = 90 days. @mat-shyR can you please investigate?

We will come back to you when we get the answer.

**Comment by oualib** [comment]
It seems to be a more a server related issue. I've opened a JIRA.

@mfelici our Vertica expert showed me a useful example.

If you run the following query, you can see what is the actual problem:

SQL> SELECT DATE'2023-02-01' - INTERVAL '3 months' ;
?column?           
-------------------
2022-11-03 00:00:00
--- 1 row(s) selected in 0.010s (prep 0.003s, exec 0.007s, fetch 0.000s/0.000s)

So Vertica seems to convert the intervals to seconds/days ... before doing the maths.

In your case, you can use a ROWS window rather than a RANGE as your data are regularly spaced (1 month step).

**Comment by oualib** [comment]
@afard & @glarik can you please look at this issue and see what we can do?
