### ISSUE TITLE
Support for converting vDataFrame to polars.DataFrame?

### ISSUE THREAD

**Issue by shane-breeze** [vertica/VerticaPy#690]
Is there any plans to support converting a vDataFrame into a [polars](https://www.pola.rs).DataFrame? I'm especially interested in converting to a polars.LazyFrame if there is a way to stream results from a vDataFrame to a polars.LazyFrame.

Unfortunately, polars does not currently support reading from vertica.

**Comment by oualib** [comment]
Hi,
I think it is possible. But why not converting the vDataFrame to a PandasDataFrame then to a LazyFrame?
```
polars.LazyFrame(vdf['col1', 'col2'].to_pandas()) 
```
Or do you need something more specific?

**Comment by shane-breeze** [comment]
Hi,

That will definitely work. But for this will load all the data into pandas so won't work well for large amounts of data. Also, since the data is loaded into memory with pandas, there is no advantage of using Polars.LazyFrame rather than Polars.DataFrame

**Comment by oualib** [comment]
What is the most optimised way to build a Polars.LazyFrame? Do they read some kind of compressed data? Do you have an example?

**Comment by oualib** [comment]
@shane-breeze I still do not get the advantage of Polars.LazyFrame over vDataFrame as vDataFrame is also lazy, it will send the query to compute the result only when it is needed. Besides, I see no example of Lazy DataFrame on data directly in DB. Besides, in that case, the query should be to implement Vertica support for LazyFrame and the issue should be raised in their Github page.

@shane-breeze can you please show me some examples to understand? Otherwise, I'll close the issue.

**Comment by oualib** [comment]
@shane-breeze I don't see how we can build an optimisation in our end. It will still need data transfer and in-memory processing. Polar needs to create a better integration with relational DB. I close this issue.
