### ISSUE TITLE
Unable to create Model.

### ISSUE THREAD

**Issue by SMoazzamR** [vertica/VerticaPy#8]
I am trying to create an RF_CLASSIFIER It throws the error LENGTH OF TYPE VARBINARY CANNOT EXCEED......  as shown in image attached. 
Detailed status of execution and failure is described as follows;
                       max_depth     independent_columns           EXECUTED
some value<=10                  236                                           yes
                       20                  20                                             yes
some value>=20                  236                                          no
max_depth<=10 and 236 independent columns.

![image](https://user-images.githubusercontent.com/58803788/88480006-b0ed9800-cf6c-11ea-9601-5c7c5672e5ec.png)

**Comment by Dillon-git** [comment]
What is the version of Vertica you are using?

**Comment by SMoazzamR** [comment]
Vertica Analytic Database v9.2.0-0

**Comment by oualib** [comment]
Hi @SMoazzamR,
We are correcting this issue at the moment. It seems that Vertica has a limit for the length of the Varbinary it is using to store the different predictors names. We will come back to you when it is solved.

**Comment by afard** [comment]
The in-DB RF algorithm internally uses LONG VARBINARY (max size 32,000,000 bytes) for transferring tree structures between UDFs. For big values of max_depth when the tree is bushy, the size of a tree might become bigger than the limited capacity of a LONG VARBINARY. The above failure had happened in such a circumstance.
It is fixed in Vertica version 10.0.1-3 such that the algorithm automatically stops growing the tree before its size go beyond the limit. Therefore, the training of the RF model can be finished smoothly.
